### ISSUE TITLE
Additional Example request using API Properties

### ISSUE THREAD

**Issue by karthickvkumar** [philipshurpik/react-native-animated-tabs#1]
Hi @philipshurpik, thanks for this awesome package. I had a scenario, where each tab has "next button". When ever the user click the button it should move to next tab. I would be very helpful if you provide me some solution for this scenario  

Thanks in Advance

**Comment by philipshurpik** [comment]
Hi @karthickvkumar :)

I have slightly improved animated tabs - so they can handle outer change of activePanel

+ Improved example, so you can see how to use it

**Comment by karthickvkumar** [comment]
Thanks @philipshurpik
